builds:
  - id: linux-amd64
    builder: prebuilt
    goos:
      - linux
    goarch:
      - amd64
    goamd64: [ 'v1' ]
    prebuilt:
      path: ./build/{{ .Arch }}/lts-advanced-plugin-dummy.so
    binary: lib-lts-advanced-plugin-dummy.so

  - id: linux-arm64
    builder: prebuilt
    goos:
      - linux
    goarch:
      - arm64
    prebuilt:
      path: ./build/{{ .Arch }}/lts-advanced-plugin-dummy.so
    binary: lib-lts-advanced-plugin-dummy.so

archives:
  - id: linux
    allow_different_binary_count: true
    builds:
      - linux-amd64
      - linux-arm64
    files:
      - LICENSE.txt
      - README.md
sboms:
  - artifacts: archive
signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
